command: ["python", "entrypoint.py"]

env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: "d85fb7ed40320552"

resources:
  - name: jayd-warehouse
    sql_warehouse:
      id: d85fb7ed40320552
      permission: CAN_USE
  - name: jayd-serving
    serving_endpoint:
      name: databricks-meta-llama-3-3-70b-instruct
      permission: CAN_QUERY
